### ISSUE TITLE
Security Profiles?

### ISSUE THREAD

**Issue by PenguinzTech** [networktocode/fortimanager-ansible#44]
Greetings,
I am in desperate need for an ansible module to apply Security profiles and groups to rules which match a destination address or interface. I cannot seem to find this as part of this module, or anything security related. Is this possible? If not, perhaps a feature request (which I can help put hours against) ?

**Comment by jmcgill298** [comment]
@theshades is this additional parameters to the fortimgr_policy module, or would this be for new modules?
