### ISSUE TITLE
fortimgr_lock "save_config" parameter code/doc discrepancy

### ISSUE THREAD

**Issue by jcsicard** [networktocode/fortimanager-ansible#48]
fortimgr_lock module documentation (https://github.com/networktocode/fortimanager-ansible/blob/master/Module_Docs/fortimgr_module_docs.md#fortimgr_lock)  list the "save_config" parameter but the code looks for the "save" parameter.

**Comment by jmcgill298** [comment]
This was updated last week; do you have the latest?

**Comment by jmcgill298** [comment]
Ah, thanks for the updated location; I will fix that also

**Comment by jmcgill298** [comment]
updated Module_Docs/
