### ISSUE TITLE
Get configuration of managed FortiGates in running-config format

### ISSUE THREAD

**Issue by phandox** [networktocode/fortimanager-ansible#55]
Hello,

I've used `fortimgr_facts` to get configuration of FortiGate managed by FortiManager, however I get it in dictionary format of Ansible. Is it possible to get the output in the same format as you would get when you issues `show` command on FortiGate? I would like to use Ansible to download the configurations of FortiGates from FortiManager (I can access the configuration via UI in Device Manager -> Revision History -> Show Configuration). When I get this output I can use it to restore configuration in case of changing hardware.

Thanks.

**Comment by jmcgill298** [comment]
What is the rpc url to access this info with the api?

**Comment by phandox** [comment]
Unfortunatelly I don't have access to Fortinet Developer Network so I can't tell you which RPC URL would that be...

**Comment by jmcgill298** [comment]
I have looked through the API documentation, and I do not see anything available to retrieve the info you are looking for. If you have a support contract with Fortinet, then maybe you can ask through the support channel.

**Comment by jmcgill298** [comment]
@phandox any luck going through your support contract?

**Comment by phandox** [comment]
Hi, sorry for late answer. No luck from Fortinet support, they just directed me to executing scripts directly on FortiManager...
