### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by fortinetps** [networktocode/fortimanager-ansible#66]
Sorry to mark this as an issue, would you please attach a LICENSE file for this project? For user to properly use or distribute these modules? I know on every module python file, there is a header with license term, it would be great if you can attach a license file I think. I noticed on other projects from your NTC company, you use Apache license instead of GNU license. Thanks!

**Comment by jmcgill298** [comment]
https://github.com/networktocode/fortimanager-ansible/commit/01d2f491ca8c6606a1da2a813cb24aaa8d366dc9
