### ISSUE TITLE
fortimgr_policy module don't support policy packages in folders

### ISSUE THREAD

**Issue by SteveRodrigue** [networktocode/fortimanager-ansible#67]
When using a folders in policy package management, the module fortimgr_policy fails.

VARS:
`vip_list.package:  "folder/policy_package_name"`
^^^ Note the var contain a "/".

PLAYBOOK:
```
 - name: Create policy for VIP
    fortimgr_policy:
      <<: *fmg_login
      package: "{{ vip_list.package }}"  
```

PLAYBOOK RUN 

```
TASK [Create policy for VIP] *****************************************************************************************************************************************************************
Friday 26 April 2019  19:09:23 +0000 (0:00:01.709)       0:00:03.787 **********
fatal: [fortigate.domain.com]: FAILED! => changed=false
  fortimanager_response:
    result:
    - status:
        code: -3
        message: Object does not exist
      url: /pm/config/adom/vdom/pkg/folder\/policy_package_name/firewall/policy
  msg: Unable to Apply Config 
```
^^^ As you can see, when running the Playbook, the module add a backslash in front of the slash (it adds an escape character).

We've been able to "fix" the problem by replacing a line of code in fortimgr_policy.py file. We basically got rid of the "/" to "\/" replacement.

fortimgr_policy.py (start at line 1566):
```
    def _escape_params_url(self, url):
        """
        This private method is used to escape slash ("/") characters from a url string to be provided as a json-rpc request params.
        Slash characters are escaped by prefixing with a backslash ("\").
        If url is None, None is returned.

        :param url: Type str.
                        The url string to process.
        :return: The url string with slash characters escaped with a backslash ("\") or None if url is None.
        """
        if url is not None:
            #return str(url).replace('/', '\\/')  <---- Original line
            return str(url)     # <---- Temporary Fix!
        else:
            return None 
```

In my opinion, the module should support folders. The best solution would probably be to add a folder parameter to the module.  So, you could still do the "escaping" while being able to add folders.

```
 - name: Create policy
    fortimgr_policy:
      folder: "{{ package_folder }}"
      package: "{{ package_name }}"
```

In Python:
`return str(folder)+"/"+str(url).replace('/', '\\/')`
instead of
`return str(url).replace('/', '\\/')`

**Comment by SteveRodrigue** [comment]
My proposed fix does not take into consideration the rest of the module code/behaviour.  I haven't done any code analysis, we just focused on getting the module work in our context.

**Comment by jmcgill298** [comment]
https://github.com/networktocode/fortimanager-ansible/commit/8978bc32b31652c8d5d46213d1da8c0ff1161965 was added as there were issues by not escaping the slashes. The solution would require adding a new parameter and to account for the folder.

**Comment by SteveRodrigue** [comment]
I just looked at the commit. A lot was added/changed in the module to add this "escaping".

A definitive fix would require some code analysis. I'll check with my team if someone could look at your module. 

We will use folders more and more. This would be nice addition to this module.

**Comment by jcsicard** [comment]
Yeah I've stumbled upon this one also after my escape commit.  I've fixed it on my side by simply not escaping the pkg_url param, as the package name can't actually have a '/' in it so the original behaviour of letting the slash go through to represent the folder hierarchy is fine.  I haven't had time to submit a PR but this is the line to change back:

`self.pkg_url = "/pm/config/adom/{}/pkg/{}/firewall/{}".format(self._escape_params_url(self.adom), self.package, self.api_endpoint)`
