### ISSUE TITLE
fmgr_fwobj_address Module not working in Ansible 2.9 - MODULE FAILURE\nSee stdout/stderr for the exact error"

### ISSUE THREAD

**Issue by Sethueha** [networktocode/fortimanager-ansible#80]
Summary: 

I have an Fortimanager VM with trail license running on it. I'm trying to configure address in device using fmgr_fwobj_address module, but it is not working. I have super user access to Fortimanager and able to do SSH from Ansible server.

Ansible version:

ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sysadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

STEPS TO REPRODUCE
Playbook:

---
- hosts: FortiManager
  connection: httpapi
  gather_facts: False
  tasks:
  - name: Create address object in Fortimanager
    fmgr_fwobj_address:
      adom: "Global"
      name: test
      ipv4: ipmask
      ipv4addr: 10.10.10.10/32
      associated_interface: any
      color: 4
      mode: add

Inventory file:

[FortiManager]
172.20.32.200 ansible_host=172.20.32.200

[fmgr_api:children]
FortiManager

[fmgr_api:vars]
ansible_network_os=fortimanager
ansible_user=admin
ansible_password=admin
ansible_become=no
ansible_become_method=disable
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
ansible_httpapi_timeout=300

EXPECTED RESULTS:
The playbook should configure the address in Fortimanager

ACTUAL RESULTS:

fatal: [172.20.32.200]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/sysadmin/.ansible/tmp/ansible-local-252351JU_df/ansible-tmp-1574851380.58-52172427055422/AnsiballZ_fmgr_fwobj_address.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/sysadmin/.ansible/tmp/ansible-local-252351JU_df/ansible-tmp-1574851380.58-52172427055422/AnsiballZ_fmgr_fwobj_address.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sysadmin/.ansible/tmp/ansible-local-252351JU_df/ansible-tmp-1574851380.58-52172427055422/AnsiballZ_fmgr_fwobj_address.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.fortimanager.fmgr_fwobj_address', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_fmgr_fwobj_address_payload_gjnAbb/ansible_fmgr_fwobj_address_payload.zip/ansible/modules/network/fortimanager/fmgr_fwobj_address.py\", line 668, in <module>\n  File \"/tmp/ansible_fmgr_fwobj_address_payload_gjnAbb/ansible_fmgr_fwobj_address_payload.zip/ansible/modules/network/fortimanager/fmgr_fwobj_address.py\", line 658, in main\nansible.module_utils.network.fortimanager.common.FMGBaseException: An attempt was made at communicating with a FMG with no valid session and an unexpected error was discovered.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

**Comment by Sethueha** [comment]
Hi Team,

Please provide the update ASAP.

**Comment by itdependsnetworks** [comment]
A few things to consider.
- You put this request in on a US holiday long weekend, and there have been 0 business days since then
- You have not formatted your issue correctly (using triple backticks) which makes it difficult to read the stacktrace.
- There seems to be a misunderstanding on the open source support model. Here is a good reference https://snarky.ca/setting-expectations-for-open-source-participation I would look at section 6

**Comment by jmcgill298** [comment]
These modules do not support the `httpapi` connection plugin; you will need to either use a token or basic auth for each task

**Comment by Sethueha** [comment]
I have referred to the link below and they have mentioned to use httpapi instead of connection local. The basic auth doesn't work with this module because it don't have option to enter host, username and password. Could you please provide one example how we have to use this,

https://ftnt-ansible-docs.readthedocs.io/en/latest/fmgr_getting_started.html

**Comment by jmcgill298** [comment]
The modules that link refers to are not related to this project, and looking back at your example, the module you are using is not part of this project. Please raise an issue with [Ansible](https://github.com/ansible/ansible/issues)
