### ISSUE TITLE
FMG behavior change: fortimgr_ip_pool_map errors (FMG -9998) when creating ippool dynamic mapping

### ISSUE THREAD

**Issue by jcsicard** [networktocode/fortimanager-ansible#82]
Used to be able to directly create/add an ip pool with only dynamic mappings with fortimgr_ip_pool_map without specifying ip pool default mapping values like below, but it doesn't work anymore (FMG v6.0.?) and returns a FMG returns -9998 error "start ip should be set".

{
  "params": [{
    "url": "/pm/config/adom/MYADOM/obj/firewall/ippool",
    "session": "xxxxxxxxxxxxx",
    "data": {
      "dynamic_mapping": [{
        "endip": "1.1.1.1",
        "_scope": [{
          "name": "MYFG",
          "vdom": "MYVDOM",
        }],
        "startip": "1.1.1.1",
        "comments": "NAT",
        "permit-any-host": "enable",
        "type": "overload",
      }],
      "name": "DFLT-OUT-NAT"},
  }],
  "method": "add",
}

{ "result": [{ 
    "status": { 
      "code": -9998, 
      "message": "firewall\/ippool\/DFLT-OUT-NAT\/ : ippool \"DFLT-OUT-NAT\": start ip should be set",
    }, 
    "url": "\/pm\/config\/adom\/MYADOM\/obj\/firewall\/ippool" 
  } ],
}
 

Same behavior is also true from the GUI.

Seems that in a recent FMG version (I just noticed on 6.0.7), the behaviour changed and you are now required to switch the "configure default value" to "off" to be able to do so.

This however isn't reflected on the API docs.

Seems that to do the same with the API, you need to set the undocumented parameter "_if_no_default" to 1 to restore the same previous behavior.

 

{

            "method": "add",
            "params": [
                {
                    "data": {
                        "_if_no_default": 1,
                        "dynamic_mapping": [
                            {
                                "_scope": [
                                    {
                                        "name": "MYFG",
                                        "vdom": "MYVDOM"
                                    }
                                ],
                                "comments": "NAT",
                                "endip": "1.1.1.1",
                                "permit-any-host": "enable",
                                "startip": "1.1.1.1",
                                "type": "overload"
                            }
                        ],
                        "name": "DFLT-OUT-NAT"
                    },
                    "url": "/pm/config/adom/MYADOM/obj/firewall/ippool"
                }
            ],

}

**Comment by jmcgill298** [comment]
#83
